In [19]:
import pandas as pd
import requests
import json

In [2]:
df = pd.read_csv('/Users/anvikshamiddha/Desktop/ML-Crate/Uber Pickup Analysis/Dataset/other-Federal_02216.csv')
df.head()

,Date,Time,PU_Address,DO_Address,Routing Details,PU_Address.1,Status
0,07/01/2014,07:15 AM,"Brooklyn Museum, 200 Eastern Pkwy., BK NY;","1 Brookdale Plaza, BK NY;","PU: Brooklyn Museum, 200 Eastern Pkwy., BK NY;...","Brooklyn Museum, 200 Eastern Pkwy., BK NY; DO:...",Cancelled
1,07/01/2014,07:30 AM,"33 Robert Dr., Short Hills NJ;","John F Kennedy International Airport, vitona A...","PU: 33 Robert Dr., Short Hills NJ; DO: John F ...","33 Robert Dr., Short Hills NJ; DO: John F Kenn...",Arrived
2,07/01/2014,08:00 AM,"60 Glenmore Ave., BK NY;","2171 Nostrand Ave., BK NY;","PU: 60 Glenmore Ave., BK NY; DO: 2171 Nostrand...","60 Glenmore Ave., BK NY; DO: 2171 Nostrand Ave...",Assigned
3,07/01/2014,09:00 AM,"128 East 31 St., BK NY;","369 93rd St., BK NY;","PU: 128 East 31 St., BK NY; DO: 369 93rd St., ...","128 East 31 St., BK NY; DO: 369 93rd St., BK NY;",Assigned
4,07/01/2014,09:30 AM,"139-39 35 Ave., Flushing NY;",La Guardia Airport;,"PU: 139-39 35 Ave., Flushing NY; DO: La Guardi...","139-39 35 Ave., Flushing NY; DO: La Guardia Ai...",Assigned

In [17]:

for i, row in df.iterrows():
    api_address = str(df.at[i, 'PU_Address']) 


    parameters = {
        "key" : "lDpi1vuQUjWhGaMuGE7hfC4UAtTAR6N2",
        "location" : api_address 
    }

    response = requests.get("http://www.mapquestapi.com/geocoding/v1/address", params = parameters)
      

    data = json.loads(response.text)['results']
    
    if api_address:
        lat = data[0]['locations'][0]['latLng']['lat']
        lng = data[0]['locations'][0]['latLng']['lng']
            
    else:
        data = {}


    df.at[i, 'lat'] = lat
    df.at[i, 'lng'] = lng
    


df.to_csv()

,Date,Time,PU_Address,DO_Address,Routing Details,PU_Address.1,Status,lat,lng
271,09/25/2014,12:00 PM,"907 59 St., BK NY; ST: W66 St./Broadway, NY NY;",John F Kennedy International Airport;,"PU: 907 59 St., BK NY; ST: W66 St./Broadway, N...","907 59 St., BK NY; ST: W66 St./Broadway, NY NY...",Arrived,40.75150,-73.90274
272,09/26/2014,04:00 PM,"20 West St., NY NY;",La Guardia Airport;,"PU: 20 West St., NY NY; DO: La Guardia Airport;","20 West St., NY NY; DO: La Guardia Airport;",Assigned,40.70625,-74.01607
273,09/27/2014,05:00 AM,"474 Sackett Street, BK NY;","John F Kennedy International Airport, Virgin A...","PU: 474 Sackett Street, BK NY; DO: John F Kenn...","474 Sackett Street, BK NY; DO: John F Kennedy ...",Arrived,40.68081,-73.98970
274,09/27/2014,08:00 AM,"474 Sackett Street, BK NY;","Newark Liberty International Airport, Virgin A...","PU: 474 Sackett Street, BK NY; DO: Newark Libe...","474 Sackett Street, BK NY; DO: Newark Liberty ...",Arrived,40.68081,-73.98970
275,09/28/2014,09:00 PM,"152 7 Ave., BK NY;",Grand Central Station ;,"PU: 152 7 Ave., BK NY; DO: Grand Central Stati...","152 7 Ave., BK NY; DO: Grand Central Station ;",Assigned,40.67246,-73.97691